PRAGMA foreign_keys = 0;

BEGIN TRANSACTION;

CREATE TABLE cats (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user BIGINT NOT NULL, cat_name TEXT NOT NULL, sadness INT DEFAULT 0 NOT NULL );

COMMIT TRANSACTION;

PRAGMA foreign_keys = 1;
